### ISSUE TITLE
Unexpected epoch change

### ISSUE THREAD

**Issue by ninabreznik** [playproject-io/datdot-substrate#13]
I noticed my chain starts to behave weird if I let it run for a long time (might be I send to many transactions triggering same function with same account too many times)
![Screenshot_2019-12-27_23-46-53](https://user-images.githubusercontent.com/1076427/71525235-55d6c280-2903-11ea-8c16-4d573e578cdc.png)

**Comment by joshua-mir** [comment]
this happens if your machine goes to sleep or the system time otherwise doesn't match the time onchain (long enough for you to be in the next epoch onchain) - this never happens if there is at least one block producer online.

workaround is to purge-chain, there's no recovery for this scenario unless you manually change your system time, unfortunately 😅
